[arq]
arq.emanuel.sarah.devops ansible_host=192.168.56.121

[db]
db.emanuel.sarah.devops ansible_host=192.168.56.131

[app]
app.emanuel.sarah.devops ansible_host=192.168.56.111

[cli]
cli.emanuel.sarah.devops ansible_host=127.0.0.1 ansible_port=2200 ansible_user=vagrant ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key

[servidores:children]
arq
db
app
cli

[servidores:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=~/.vagrant.d/insecure_private_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
